definitions:
  entity.User:
    properties:
      email:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/company/user/login:
    get:
      description: Retrieves the list of users who has to login in the app
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
      summary: Retrieves the list of users who has to login in the app
  /api/v1/company/user/register:
    get:
      description: Retrieves the list of users who has to register in the app
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
      summary: Retrieves the list of users who has to register in the app
swagger: "2.0"
